### ISSUE TITLE
Open diagram in draw.io desktop

### ISSUE THREAD

**Issue by ghost** [laingsimon/draw-ship#3]
Add option to open the diagram in [draw.io desktop](https://github.com/jgraph/drawio-desktop), if installed.

Draw.io desktop installs to `C:\Program Files\draw.io` by default.

Ideally context-menu default would be set to open in draw.io desktop by default.

**Comment by laingsimon** [comment]
Closing as an unworthy feature.
User can install draw.io desktop and associate the application with .xml / .drawio files to achieve this behaviour.
