### ISSUE TITLE
Image/Print options should operate on the current page

### ISSUE THREAD

**Issue by ghost** [laingsimon/draw-ship#6]
```gherkin
Given I have a diagram with several pages
And I select a different page (not the first page)
And I choose to render the diagram as an image (clicking the Image link)
Then I expect the diagram on the current page to be rasterised
```

```gherkin
Given I have a diagram with several pages
And I select a different page (not the first page)
And I choose to print the diagram (clicking the Print link)
Then I expect the diagram on the current page to be printed
```

**Comment by ghost** [comment]
Still not working correctly

**Comment by laingsimon** [comment]
Confirmed to work for print & image functions with sample file

**Comment by laingsimon** [comment]
`Sample file.xml` has been updated and issue can be reproduced, appears to be due to the naming of pages (either when they contain a `(` or `)` character.

Bug will need to be raised with [jGraph/imageExport](https://github.com/jgraph/draw-image-export2/).

**Comment by laingsimon** [comment]
Comment from issue: https://github.com/jgraph/draw-image-export2/issues/4

> The pageId parameter requires the ID of the page, not the page number.

**Comment by laingsimon** [comment]
Pages should be selected by `id` not by their `name`.
